fstab parser
demostanis/userspace_digressions pull request #1
Opened 2024-07-14 17:13 UTC by DinoMalin

+ fstab parser
+ swap

2024-07-15 03:43 UTC, demostanis requested changes
go fmt

2024-07-15 03:43 UTC, demostanis commented on custom/etc/textfile
> +Omar est une fraude intersiderale
gros tes bourré ou quoi pourquoi tu te prends pour un fichier texte

2024-07-15 03:43 UTC, demostanis commented on internal/fstab/fstab.go
> +	for _, opt := range opts {
jveux une explicatiin de pourquoi ya besoin des flags et pas "psk chatgpt"

2024-07-15 03:43 UTC, demostanis commented on internal/fstab/fstab.go
> +			// Ignore, implicit if not noexec
chatgpt leftover

2024-07-15 03:43 UTC, demostanis commented on internal/fstab/fstab.go
> +func MountMP(mp *MountPoint) error {
func (m *Mountpoint) Mount

2024-07-15 03:43 UTC, demostanis commented on internal/fstab/fstab.go
> +		if err.Error() == "no such file or directory" {
fais pas ça

2024-07-15 03:43 UTC, demostanis commented on internal/fstab/fstab.go
> +	fstab, err := parser.ParseString("", content_str)
ya pas de parsebytes?

2024-07-15 03:43 UTC, demostanis commented on internal/fstab/fstab.go
> +		participle.UseLookahead(2),
pourquoi du lookahead pour juste des items séparés apr des espaces (et me dis pas "psk exemple github bla ba bla" -42)

2024-07-15 03:43 UTC, demostanis commented on internal/swap/swap.go
> +	cmd := exec.Command("swapon", "/dev/sdb")
hardcoder ça cest bof... pourquoi tu regardes pas le fstab???

2024-07-15 03:43 UTC, demostanis commented on vm.sh
> +swap_name=swap
pourquoi le gitignore il a un swap.qcow2???

2024-07-15 03:43 UTC, demostanis commented on vm.sh
> +chmod 600 $swap_name
mets des double quotes pour garder dla consistance avec iso_name

2024-07-15 03:43 UTC, demostanis commented on vm.sh
> +	qemu-img create $swap_name $swap_size
dd cest pas assez? qemu-img fait quoi de plus?

2024-07-15 03:43 UTC, demostanis commented on vm.sh
> +# dd if=/dev/zero of="$tmp"/swap bs=1M count=1
commment leftover?

2024-07-15 18:25 UTC, DinoMalin commented on vm.sh
> +	qemu-img create $swap_name $swap_size
La commande existe pour qemu directement autant l'utiliser
+ J'arrivais pas a utiliser dd

2024-07-15 18:26 UTC, DinoMalin commented on vm.sh
> +swap_name=swap
hein

2024-07-15 18:26 UTC, DinoMalin commented on internal/fstab/fstab.go
> +		if err.Error() == "no such file or directory" {
si

2024-07-15 18:28 UTC, DinoMalin commented on internal/fstab/fstab.go
> +			// Ignore, implicit if not noexec
nn jtrouvais moche sans rien

2024-07-15 18:30 UTC, DinoMalin commented on internal/fstab/fstab.go
> +	for _, opt := range opts {
Parce que la fonction Mount d'unix prend des flags en parametres ??

2024-07-15 18:30 UTC, DinoMalin commented on custom/etc/textfile
> +Omar est une fraude intersiderale
jsp frr g oublie

2024-07-15 21:08 UTC, DinoMalin commented on internal/fstab/fstab.go
> +	fstab, err := parser.ParseString("", content_str)
C'est ce qui est utilise dans la doc de participle

2024-07-15 21:09 UTC, DinoMalin commented on internal/fstab/fstab.go
> +		participle.UseLookahead(2),
j'en sais rien gros c'est le seul truc qui marchait

2024-08-08 12:02 UTC, DinoMalin commented on internal/fstab/fstab.go
> +	for _, opt := range opts {
apres de plus amples recherches j'ajouterais que les flags c'est les options basiques que tu peux filer a mountpoint (exec, no exec...)
Les options c'est pour des trucs plus precis (ex : uid=1000)

2024-08-26 19:22 UTC, closed without merging